Add XCI rom format support
skyline-emu/skyline pull request #137
Opened 2021-03-06 14:53 UTC by sspacelynx

2021-03-06 15:14 UTC, bylaws requested changes

2021-03-06 15:14 UTC, bylaws commented on app/src/main/cpp/skyline/loader/xci.cpp
> +        } else throw exception("Corrupted secure partition");
Newline after else

2021-03-06 15:14 UTC, bylaws commented on app/src/main/cpp/skyline/loader/xci.cpp
> +
Drop this space

2021-03-06 15:37 UTC, sspacelynx commented on app/src/main/cpp/skyline/loader/xci.cpp
> +
oops didn't see this

2021-03-06 15:39 UTC, sspacelynx commented
Fixed up changes as the commit was too small to justify

2021-03-07 15:34 UTC, PixelyIon requested changes
A single change, that's it

2021-03-07 15:50 UTC, sspacelynx commented on app/src/main/cpp/skyline/loader/xci.cpp
> +            throw exception("Corrupted secure partition");
Missed that

2021-03-07 15:52 UTC, sspacelynx commented
Done!

2021-03-07 16:52 UTC, PixelyIon approved these changes
Great job! This is exactly how we wanted it to be implemented :star:

2021-03-07 16:53 UTC, bylaws approved these changes
Good

2021-03-07 17:25 UTC, merged