Use spans instead of ptr and size in kernel memory
skyline-emu/skyline pull request #1487
Opened 2022-06-06 18:34 UTC by MCredstoner2004

This makes the code more readable and allowed removing a bunch of one-liner functions

2022-06-06 18:38 UTC, bylaws commented on app/src/main/cpp/skyline/kernel/memory.cpp
> +                addressSpace = span<u8> {static_cast<u8 *>(nullptr), 1UL << 36};
don't do this, best to do size seperate and add ptr to construct a span after

2022-06-06 18:39 UTC, bylaws commented on app/src/main/cpp/skyline/kernel/memory.cpp
> +        auto offset{static_cast<size_t>(mapping.data() - base.data())};
cast not needed

2022-06-06 18:40 UTC, bylaws commented on app/src/main/cpp/skyline/kernel/memory.cpp
> +            size_t offset{static_cast<size_t>(region.data() - base.data())};
cast not needed

2022-06-06 18:43 UTC, bylaws requested changes
this code is pretty cute

2022-06-06 18:43 UTC, bylaws commented on app/src/main/cpp/skyline/kernel/types/KPrivateMemory.cpp
> +        auto pPtr = std::clamp(map.data(), guest.data(), guest.end().base());
drop p and use {}, p is for parameters and it's no longer from a parameter henc enot needed

2022-06-06 18:43 UTC, bylaws commented on app/src/main/cpp/skyline/kernel/types/KProcess.cpp
> +        heap = std::make_shared<KPrivateMemory>(state, span<u8>(reinterpret_cast<u8 *>(state.process->memory.heap.data()), DefaultHeapSize), memory::Permission{true, true, false}, memory::states::Hea
use {} init for all spans

2022-06-06 18:43 UTC, bylaws commented on app/src/main/cpp/skyline/kernel/types/KSharedMemory.cpp
> +        host = span<u8>(host_ptr, size);
{}

2022-06-06 18:43 UTC, bylaws commented on app/src/main/cpp/skyline/kernel/types/KSharedMemory.cpp
> +        auto guest_ptr = static_cast<u8 *>(mmap(map.data(), map.size(), permission.Get(), MAP_SHARED | (map.data() ? MAP_FIXED : 0), fd, 0));
guestPtr

2022-06-06 22:20 UTC, bylaws commented on app/src/main/cpp/skyline/kernel/types/KSharedMemory.cpp
> +        auto guestPtr = static_cast<u8 *>(mmap(map.data(), map.size(), permission.Get(), MAP_SHARED | (map.data() ? MAP_FIXED : 0), fd, 0));
use {}

2022-06-09 16:50 UTC, PixelyIon requested changes
There is a very large amount of nits to fix here, it'll take you a while. Good luck!

2022-06-10 06:02 UTC, PixelyIon approved these changes
Great job, LGTM! I'll merge after you rebase onto `ftx1`.

2022-06-10 18:23 UTC, bylaws approved these changes

2022-06-10 19:20 UTC, merged