Follow industry standard version formatting
skyline-emu/skyline pull request #1805
Opened 2022-08-21 12:33 UTC by AbandonedCart

Not fond of claiming ownership of what is fundamentally just moving code around, but the appearance of the current layout where the version number is appended to the bottom looks awkward. This moves the version number between the title and the developer / distributor, which is the typical format for such information.

Message: The structure of the UI is just as important to the end user as the structure of code is to developers, so this will format the details in the expected order visually and move the code to match the updated placement.

2022-08-21 12:37 UTC, lynxnb commented
Appreciate the PR, would you mind posting a screenshot?

2022-08-21 13:11 UTC, AbandonedCart commented
![Screenshot_20220821-085931_Skyline](https://user-images.githubusercontent.com/1173913/185792402-5efd1d5a-3dbb-480f-a773-b419d4d1fdda.png)

It's swapping the last two lines. Really basic.

2022-08-21 14:47 UTC, AbandonedCart commented
In defense of the original layout, a lot of "distribution" sites list the version after the publisher because the release date is used to "version" the entire game. Links to the same listing are formatted as the name and version number. Official sites replace the version number with the release date entirely. What is shown to the user is not the complete game as a sum of its parts and release dates are not displayed, so the assumption is that it most resembles a link or file.

You would ideally launch the original file, but with a version number of the latest update (once all that is supported). The original file won't natively have the update number and the update won't be launched directly. It ends up confusing a lot of people explaining that they need to launch 1.0.0 and the update will be applied or you have to pull version numbers from the update files and find the latest to display over the main icon. That is probably why they usually aren't displayed.

2022-08-22 19:35 UTC, Uukspppqi commented
Hola skyline

2022-08-23 15:08 UTC, AbandonedCart commented
https://github.com/skyline-emu/skyline/commit/5d6eaee301f770245ebfa69307d2d37e5b159c66 explains why it seemed like the author was being checked and version wasn't. I didn't want to go changing code when all I was proposing is restructuring placement.

2022-08-23 17:53 UTC, lynxnb commented
I'll be doing a review of this as soon as I find some free time.

2022-08-23 19:58 UTC, AbandonedCart commented
Literally moved code from one line to another, so that is probably best taken up with #175.

2022-08-23 20:29 UTC, lynxnb commented
Reopened because I do think this PR adds some value even if it's just "moving code around". As maintainers, we can edit code and commits while still keeping you as author, so I can do that if you really have no time.

I was targeting to merge this rather quickly, I'll do a review in a few hours, let me know if you are available or if I should just fix the nits myself.

2022-08-23 21:07 UTC, AbandonedCart commented
I wasn't trying to rush you. It was really more or less just that it "looked cleaner" not having a trailing version, but with some semi-rational logic to back it up. It isn't something I wanted anyone wasting more than 5 minutes on and could be circled back to later. Closing a PR doesn't delete it, just takes it out of the pending state.

If it really means that much to you, go ahead and propose your changes. It is because I understand being a maintainer that I favored saving the time.  Not sure if you have any plans to release on Google Play, but wasting time is something they specialize in doing.

2022-08-25 12:07 UTC, lynxnb requested changes
Code looks good apart from minor nits, but they are not your fault as they were probably put in previously by Android Studio.

2022-08-25 12:07 UTC, lynxnb commented on app/src/main/res/layout/app_item_linear.xml
> +        app:layout_constraintBottom_toTopOf="@+id/text_version"
```suggestion
        app:layout_constraintBottom_toTopOf="@id/text_version"
```

2022-08-25 12:07 UTC, lynxnb commented on app/src/main/res/layout/app_item_linear.xml
> +        app:layout_constraintBottom_toTopOf="@+id/text_subtitle"
```suggestion
        app:layout_constraintBottom_toTopOf="@id/text_subtitle"
```

2022-08-25 12:07 UTC, lynxnb commented on app/src/main/res/layout/app_item_grid_compact.xml
> +            app:layout_constraintBottom_toTopOf="@+id/text_subtitle"
```suggestion
            app:layout_constraintBottom_toTopOf="@id/text_subtitle"
```

2022-08-25 12:07 UTC, lynxnb commented on app/src/main/res/layout/app_item_grid_compact.xml
> +            app:layout_constraintBottom_toTopOf="@+id/text_version"
```suggestion
            app:layout_constraintBottom_toTopOf="@id/text_version"
```

2022-08-25 12:39 UTC, AbandonedCart commented
> Could you rename all occurrences of textSubtitle in Kotlin code and game_subtitle in the XML layouts with, respectively, textAuthor and game_author

Assuming you meant textSubtitle and textAuthor to game_subtitle and game_author.

2022-08-25 13:17 UTC, AbandonedCart commented
I'm fairly certain it took more time to explain those changes than to have tacked them on, but they're done. I'm not going to move forward with the line changes until someone confirms you are aware it breaks Android standards and adds instability risk. I can inject a commit, but not as a rewrite of the original code for the same reasons.

2022-08-25 13:40 UTC, AbandonedCart commented
Had to break those links so every fork or cherry-pick in the world wouldn't throw on a reference to the PR.

2022-08-27 12:47 UTC, lynxnb approved these changes
LGTM, thanks!

2022-08-27 13:24 UTC, merged