Staging asefbhjk
skyline-emu/skyline pull request #182
Opened 2021-05-27 21:30 UTC by bylaws

2021-05-27 21:30 UTC, bylaws commented
uh ignore this for the moment, i didn't mean to create this PR yet

2021-06-03 14:57 UTC, PixelyIon requested changes
A few bits, really good job aside from this though

2021-06-03 14:59 UTC, bylaws commented on app/src/main/cpp/skyline/services/am/controller/IApplicationFunctions.cpp
> +        // for us it's enough to just hash the seed from control.nacp as it provides the same guarantees.
Did this originally, it looks very ugly so splitting into two lines makes more sense

2021-06-03 15:10 UTC, PixelyIon commented on app/src/main/cpp/skyline/services/am/controller/IApplicationFunctions.cpp
> +        // for us it's enough to just hash the seed from control.nacp as it provides the same guarantees.
I really do dislike the break after a comma specifically, it looks really off. If you want to split at that point remove the comma and full-stop.

2021-06-14 10:29 UTC, bylaws commented on app/src/main/cpp/skyline/common/uuid.cpp
> +        constexpr u8 reserved{0x1}; // RFC4122 variant
I don't do it elsewhere in the file so it's best just to leave

2021-06-18 16:26 UTC, bylaws commented
done

2021-06-18 17:01 UTC, bylaws commented
!!

2021-06-18 20:22 UTC, PixelyIon commented on app/src/main/cpp/skyline/kernel/scheduler.cpp
>          if (currentIt == core->queue.begin()) {
These are heavily correlated if statements, they should be an `if else` chain

2021-06-20 13:06 UTC, PixelyIon approved these changes
LGTM!

2021-06-20 13:18 UTC, merged