stub IClient::Poll and implement IApplicationDisplayService::GetIndirectLayerImageRequiredMemoryInfo
skyline-emu/skyline pull request #1926
Opened 2022-10-26 10:06 UTC by dimaxdqwerty

These changes allow Dark Souls (maybe some other games) go to in game with save file (without save file it crashes on inline swkbd) on ftx1, didn't try with gpu-new.
P.S. I don't know what to write in @brief of GetIndirectLayerImageRequiredMemoryInfo. And I'm not cpp dev, so I'm sorry if I did something wrong.

2022-10-28 09:15 UTC, dimaxdqwerty commented
Btw, should I use s64 or u64?

2022-10-29 12:18 UTC, bylaws requested changes

2022-10-29 12:18 UTC, bylaws commented on app/src/main/cpp/skyline/services/visrv/IApplicationDisplayService.cpp
> +        auto width{request.Pop<s64>()};
i64

2022-10-29 12:18 UTC, bylaws commented on app/src/main/cpp/skyline/services/visrv/IApplicationDisplayService.cpp
> +        Logger::Debug("GetIndirectLayerImageRequiredMemoryInfo: width: {}, height: {}", width, height);
Drop function name from log

2022-10-29 12:18 UTC, bylaws commented on app/src/main/cpp/skyline/services/visrv/IApplicationDisplayService.cpp
> +        constexpr s64 base_size = 0x20000;
`        static constexpr i64 baseSize{0x20000};`
do same for all, make sure to use camelCase

2022-10-29 12:18 UTC, bylaws commented on app/src/main/cpp/skyline/services/visrv/IApplicationDisplayService.h
> +         * @brief
Just drop brief if there is none

2022-10-29 12:46 UTC, PixelyIon commented
Ignore @bylaws's CR comments, I have a proper implementation of the function. You can just drop that commit.

2022-10-29 12:47 UTC, dimaxdqwerty commented
> Ignore @bylaws's CR comments, I have a proper implementation of the function. You can just drop that commit.

done

2022-10-29 14:22 UTC, PixelyIon approved these changes

2022-10-29 14:22 UTC, merged