Add possibility to disable audio output
skyline-emu/skyline pull request #1993
Opened 2022-11-16 20:13 UTC by dimaxdqwerty

Might fix some games (e.g The Legend of Zelda: Skyward Sword HD)

2022-11-16 20:19 UTC, bylaws requested changes

2022-11-16 20:19 UTC, bylaws commented on app/src/main/cpp/skyline/audio.cpp
> +        settings = state.settings;
Use {} initialiser list

2022-11-16 20:19 UTC, bylaws commented on app/src/main/cpp/skyline/services/audio/IAudioRenderer/IAudioRenderer.cpp
> +        if (!*state.settings->isAudioOutputDisabled) {
Drop {}

2022-11-16 20:19 UTC, bylaws commented on app/src/main/java/emu/skyline/utils/NativeSettings.kt
> +    //Audio
Add space after //

2022-11-16 20:19 UTC, bylaws commented on app/src/main/java/emu/skyline/utils/PreferenceSettings.kt
> +    //Audio
Add space after //

2022-11-16 20:19 UTC, bylaws commented on app/src/main/res/values/strings.xml
> +    <string name="disable_audio_output_enabled">Audio output is disabled (Might fix some games with audio issues)</string>
Would drop the might fix...

2022-12-01 23:29 UTC, lynxnb approved these changes

2022-12-01 23:33 UTC, merged