Toggle DisableFrameThrottling setting by clicking on FPS display
skyline-emu/skyline pull request #2037
Opened 2022-12-02 08:12 UTC by darko1979

I made a suggestion few days ago about adding a toggle button for enabling/disabling frame throttling.
At first I thought about adding special button but it was easier to do it by clicking on FPS counter.
Not sure if I did it right, it was not working until I updated the setting inside presentation engine and updated the swapchain.
Tested on my phone and it seems to be working.

2022-12-02 11:00 UTC, PixelyIon commented
@lynxnb You think it's a good idea to implement this in the meantime as we don't currently have dynamic settings with callbacks?

2022-12-02 20:10 UTC, lynxnb commented
Yes I believe this could be useful in the meantime, but implementation need some work. I'll follow up with a review explaining what needs to be done (we already have a mechanism for runtime settings modification and reload).

2022-12-05 19:21 UTC, lynxnb requested changes
The `toggleDisableFrameThrottling` function should be removed in favor of adding a callback [here](https://github.com/skyline-emu/skyline/blob/ftx1/app/src/main/cpp/skyline/gpu/presentation_engine.cpp#L35) like this:
```cpp
state.settings->disableFrameThrottling.AddCallback(...);
```
Here is [AddCallback](https://github.com/skyline-emu/skyline/blob/ftx1/app/src/main/cpp/skyline/common/settings.h#L54). 

On the Kotlin side, code is not ready yet to handle updating new settings at runtime. You'd ideally just have to set the new value to SharedPreferences, then the system would automatically update settings. We'd like to have that system in place before merging this in the current state.

2022-12-06 07:16 UTC, darko1979 commented on app/src/main/java/emu/skyline/EmulationActivity.kt
> +                    var result = toggleDisableFrameThrottling()
Done, hope this is what you had in mind.

2022-12-18 20:35 UTC, bylaws commented
this doesn't seem to work for me

2022-12-18 23:22 UTC, darko1979 commented
> this doesn't seem to work for me

Original code from first commit worked for me. With requested changes only color of the FPS indicator is changing on touch because settings are not propagated to the presentation layer.

2022-12-20 13:10 UTC, lynxnb commented
It's expected for stuff to not work as of now. I'll soon add a commit to this PR wiring settings up so that they're correctly handed down to the native side. After that, things should work properly.

2023-02-06 14:05 UTC, lynxnb commented
I haven't forgotten about this, I'll add the missing piece in the following days.

2023-02-06 18:00 UTC, lynxnb commented
Done, also rebased while at it.

2023-02-07 12:14 UTC, lynxnb approved these changes

2023-02-20 21:45 UTC, merged