Added folding devices support
skyline-emu/skyline pull request #2328
Opened 2023-04-21 19:18 UTC by skriand

When app is spanned on dual-screen device (Surface Duo) or folding device is folded 90 degrees, game view is located in center of upper separate section.

2023-04-21 21:18 UTC, AbandonedCart commented
It looks like this is only supporting one specific type of hinge, but disabling the user orientation on both. To put it another way, it would work on the Flip, but on the Fold it would only ignore the user orientation setting.

2023-04-21 22:02 UTC, skriand commented
[Documentation](https://learn.microsoft.com/en-us/dual-screen/android/jetpack/window-manager/) says, that property `isSeparating` for dual-screen devices will always be true when an app is spanned across the hinge. For other foldable devices, this will only be true when the state is `HALF_OPENED`, like when a device is in the tabletop position.
So, it shouldn't disturb on the Fold.

2023-04-21 22:30 UTC, AbandonedCart commented
I think you misunderstood.

>     if (it.isSeparating) { <- this determines the device is bent
>         //Folding feature separates the display area into two distinct sections
>         requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED <- this ignores user orientation
>         if (foldFeature.orientation == FoldingFeature.Orientation.HORIZONTAL) { <- this checks the hinge axis
>                 binding.onScreenGameView.minimumHeight = displayFeature.bounds.top
>         }
>     }

The Fold is talking about the [Galaxy Z Fold](https://www.samsung.com/us/smartphones/galaxy-z-fold4/).

Per the [Android documentation](https://developer.android.com/guide/topics/large-screens/make-apps-fold-aware), [FoldingFeature.Orientation.HORIZONTAL](https://developer.android.com/reference/androidx/window/layout/FoldingFeature.Orientation#HORIZONTAL()) is one of two [FoldingFeature.Orientation](https://developer.android.com/reference/androidx/window/layout/FoldingFeature.Orientation) types. 

The code, as it is, sets the orientation to SCREEN_ORIENTATION_UNSPECIFIED for any FoldingFeature.Orientation, but only sets the bounds when the FoldingFeature.Orientation is FoldingFeature.Orientation.HORIZONTAL 

Hopefully this makes more sense.

2023-04-22 12:03 UTC, AbandonedCart commented
Wouldn't it be easier to move the original orientation override inside the condition and then add a simple true / false option to enable folding to reposition the screen?

>    private fun updateCurrentLayout(newLayoutInfo: WindowLayoutInfo) {
>        if (!appSettings.enableFolding) return

...

>     if (it.isSeparating) {
>         if (foldFeature.orientation == FoldingFeature.Orientation.HORIZONTAL) {
>                 requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED
>                 binding.onScreenGameView.minimumHeight = displayFeature.bounds.top
>         }
>     }

2023-04-22 20:57 UTC, skriand commented
Yes, it's really easier that way.

2023-04-22 21:22 UTC, AbandonedCart commented
You'd probably also want to get the height `by lazy` outside the function to spare a little memory. I didn't think of that until after, but any of that you want to use is yours.

2023-04-23 12:11 UTC, AbandonedCart commented
```
git reset --hard 4c7fd0447d7333d815d2d9e8343e5f97ae9a24d1
git cherry-pick cb6f5c5d47e274631831abdf56372df71a15db34 06635d7f69a2e2d09e60fac60d1799aa466a024c 0b71570661ac080fdc92412f0431bf6a4001b60f 79e49e03a0addd3e3cd7660e727a12c8ff239b00
git push -f
```

This will remove all of the merge messages and leave just the commits. The hashes are based on your repo.

2023-04-30 13:06 UTC, AbandonedCart commented
I made some adjustments to move the pause button and performance stats into the bottom screen. Along with that, I added a bit of a buffer to the top and bottom of the bottom screen to avoid placing buttons in the bend and having the controls at the edge of the screen. 

I can also submit this separately later to avoid it being something you have to get approved as part of this PR, since it does not replace any of the code already included.

https://github.com/8bitDream/skyline/commit/49de3856215eaf5ab508f7363d902ee2f6922592

2023-05-02 11:27 UTC, bylaws commented
@lynx

2023-05-02 11:28 UTC, bylaws commented
@lynxnb

2023-05-02 11:29 UTC, lynxnb commented
I'll get to this soon.

2023-05-02 14:10 UTC, lynxnb commented
Also, I'm not sure `Support Foldable Screens` is that good of a name, but can't think of a better one, so I guess we'll keep that. Suggestions are welcome.

2023-05-02 14:20 UTC, AbandonedCart commented
Samsung calls it Flex Mode, but that doesn't cover OPPO or Microsoft. 

Split screen sounds like the feature on any screen tall / wide enough.

The only real alternative would be using "display" instead of "screen"

2023-05-04 20:51 UTC, lynxnb requested changes

2023-05-04 20:51 UTC, lynxnb commented on app/src/main/java/emu/skyline/EmulationActivity.kt
> +        }
Would love to see some comments in here to explaining the **why** of what is being done. Unlikely anyone will remember months from now, let alone years in the future.

2026-08-18 07:17 UTC, closed without merging