Implement some IAccountServiceForApplication functions
skyline-emu/skyline pull request #443
Opened 2022-03-09 10:26 UTC by MK73DS

This PR stubs some functions in [IAccountServiceForApplication](https://switchbrew.org/wiki/Account_services#acc:u0) :
- IAccountServiceForApplication::GetUserCount (0x0)
- IAccountServiceForApplication::InitializeApplicationInfo (0x8C)
- IAccountServiceForApplication::IsUserAccountSwitchLocked (0x96)

This is required by New Pokémon Snap, implementing these services makes this game boot a bit further and display a (broken) splash screen.

![image](https://user-images.githubusercontent.com/10391562/157418335-eb20d67b-13bb-448d-970e-708c2b3602a0.png)

2022-03-09 14:06 UTC, maytinhdibo commented
great

2022-03-09 16:10 UTC, PixelyIon requested changes
Good job with this, you got all the basics of implementation right and most comments concern the specifics of comments and other minor issues.

2022-03-09 16:12 UTC, bylaws commented on app/src/main/cpp/skyline/services/account/IAccountServiceForApplication.cpp
> +        u64 pid_placeholder{request.Pop<u64>()};
Don't do that since we could need them

2022-03-09 18:52 UTC, PixelyIon approved these changes
LGTM!

2022-03-09 19:19 UTC, merged

2022-03-10 05:55 UTC, maytinhdibo commented
[FILE_20220310_125347_emulation.sklog.txt](https://github.com/skyline-emu/skyline/files/8220754/FILE_20220310_125347_emulation.sklog.txt)
Pokemon Snap still crash

2022-03-17 18:00 UTC, PixelyIon commented
@sauradipdebnath That's not how the code works, I understand you want to help but this just clogs up the repository. I will be doing a temporary ban on the next unrelated comment.