Create the IRS service and add other functions
skyline-emu/skyline pull request #492
Opened 2022-03-18 18:48 UTC by kaikecarlos

Those functions where required in order to boot DELTARUNE (is still not booting but the reason is not related to the services anymore)
    - `StartSixAxisSensor`
    - `GetVibrationDeviceInfo`
    - `IsUserRegistrationRequestPermitted`
 and the `IRS` service.

2022-03-18 18:52 UTC, bylaws commented on app/src/main/cpp/skyline/services/account/IAccountServiceForApplication.h
> +            * @brief Returns if the user registration request is permitted or not
Add a space before the *

2022-03-18 18:53 UTC, bylaws commented on app/src/main/cpp/skyline/services/hid/IHidServer.cpp
> +        return {};
This should be stubbed properly to return valid stub data rather than nothing

2022-03-18 18:53 UTC, bylaws commented on app/src/main/cpp/skyline/services/hid/IHidServer.h
> +            SFUNC(0xc8, IHidServer, GetVibrationDeviceInfo),
C8

2022-03-18 18:53 UTC, bylaws commented on app/src/main/cpp/skyline/services/irs/IIrSensorServer.cpp
> +// Copyright © 2021 Skyline Team and Contributors (https://github.com/skyline-emu/)
Hmm last time I checked it was 2022

2022-03-18 18:54 UTC, bylaws commented on app/src/main/cpp/skyline/services/irs/IIrSensorServer.h
> +        Result GetNpadIrCameraHandle(type::KSession &session, ipc::IpcRequest &request, ipc::IpcResponse &response);
Add spaces between funcs and comment formatting

2022-03-18 18:54 UTC, bylaws commented on app/src/main/cpp/skyline/services/irs/IIrSensorServer.h
> +          SFUNC(0x130, IIrSensorServer, GetIrsensorSharedMemoryHandle)
Put this first,
Otherwise code lgtm

2022-03-18 19:01 UTC, PixelyIon requested changes
This is really good for a first PR, you got almost everything right aside from minor nits that @bylaws pointed out and a few stubs not implementing enough.

2022-03-19 20:21 UTC, gustavommcv approved these changes

2022-03-19 20:24 UTC, gustavommcv approved these changes

2022-03-21 09:22 UTC, PixelyIon requested changes

2022-03-21 09:22 UTC, PixelyIon commented on app/src/main/cpp/skyline/services/irs/IIrSensorServer.cpp
> +        }
Single line `if` statements shouldn't have braces.

2022-03-21 09:22 UTC, PixelyIon commented on app/src/main/cpp/skyline/services/hid/IHidServer.cpp
> +        response.Push(NpadVibrationDeviceInfo{0,0});
It would be great if this was implemented further, reporting no vibrators here might lead to the game not submitting any vibrations.

2022-03-23 22:06 UTC, PixelyIon reviewed
LGTM!

2022-03-23 22:06 UTC, PixelyIon approved these changes
LGTM!

2022-03-27 14:42 UTC, merged