Create a building guide + update README.md
skyline-emu/skyline pull request #928
Opened 2022-04-07 13:23 UTC by lynxnb

2022-04-10 06:03 UTC, PixelyIon requested changes
Great job, I just have a couple of nits

2022-04-10 06:41 UTC, lynxnb commented on BUILDING.md
> +Import the project: click on the `Open` icon then in the file picker choose the `skyline` folder you just cloned in the steps above
I'll reword the sentence a bit to remove the colon

2022-04-14 00:05 UTC, greggameplayer commented
@lynxnb Why not doing a wiki page for the building guide instead of a markdown file ?

2022-04-14 05:52 UTC, PixelyIon commented
@greggameplayer We like documentation like that being more front and center, it being available locally on being cloned is another reason. Either way, we're unlikely to change this.

2022-04-14 05:57 UTC, PixelyIon approved these changes
This looks really nice, good job!

2022-04-14 08:24 UTC, merged